version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: local-mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: local-mongo-express
    depends_on:
    - mongo
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
    - "8081:8081"

volumes:
  mongo_data:
